/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Decision { 'firmA' : boolean, 'firmB' : boolean }
export interface PayoffMatrix {
  'defectDefectA' : bigint,
  'defectDefectB' : bigint,
  'cooperateDefectA' : bigint,
  'cooperateDefectB' : bigint,
  'cooperateCooperateA' : bigint,
  'cooperateCooperateB' : bigint,
  'defectCooperateA' : bigint,
  'defectCooperateB' : bigint,
}
export interface RoundResult {
  'cumulativeA' : bigint,
  'cumulativeB' : bigint,
  'decision' : Decision,
  'round' : bigint,
  'payoffA' : bigint,
  'payoffB' : bigint,
}
export interface SimulationResult {
  'sustainedCooperation' : boolean,
  'totalA' : bigint,
  'totalB' : bigint,
  'rounds' : Array<RoundResult>,
}
export interface _SERVICE {
  'getAnalysis' : ActorMethod<
    [],
    {
      'nashEquilibrium' : string,
      'dominantStrategyA' : string,
      'dominantStrategyB' : string,
    }
  >,
  'getPayoffMatrix' : ActorMethod<[], PayoffMatrix>,
  'getSimulationHistory' : ActorMethod<[], Array<SimulationResult>>,
  'runOneShot' : ActorMethod<[string, string], SimulationResult>,
  'runRepeatedGame' : ActorMethod<[string, string, bigint], SimulationResult>,
  'updatePayoffMatrix' : ActorMethod<[PayoffMatrix], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];