/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PayoffMatrix = IDL.Record({
  'defectDefectA' : IDL.Nat,
  'defectDefectB' : IDL.Nat,
  'cooperateDefectA' : IDL.Nat,
  'cooperateDefectB' : IDL.Nat,
  'cooperateCooperateA' : IDL.Nat,
  'cooperateCooperateB' : IDL.Nat,
  'defectCooperateA' : IDL.Nat,
  'defectCooperateB' : IDL.Nat,
});
export const Decision = IDL.Record({ 'firmA' : IDL.Bool, 'firmB' : IDL.Bool });
export const RoundResult = IDL.Record({
  'cumulativeA' : IDL.Nat,
  'cumulativeB' : IDL.Nat,
  'decision' : Decision,
  'round' : IDL.Nat,
  'payoffA' : IDL.Nat,
  'payoffB' : IDL.Nat,
});
export const SimulationResult = IDL.Record({
  'sustainedCooperation' : IDL.Bool,
  'totalA' : IDL.Nat,
  'totalB' : IDL.Nat,
  'rounds' : IDL.Vec(RoundResult),
});

export const idlService = IDL.Service({
  'getAnalysis' : IDL.Func(
      [],
      [
        IDL.Record({
          'nashEquilibrium' : IDL.Text,
          'dominantStrategyA' : IDL.Text,
          'dominantStrategyB' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getPayoffMatrix' : IDL.Func([], [PayoffMatrix], ['query']),
  'getSimulationHistory' : IDL.Func([], [IDL.Vec(SimulationResult)], ['query']),
  'runOneShot' : IDL.Func([IDL.Text, IDL.Text], [SimulationResult], []),
  'runRepeatedGame' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [SimulationResult],
      [],
    ),
  'updatePayoffMatrix' : IDL.Func([PayoffMatrix], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PayoffMatrix = IDL.Record({
    'defectDefectA' : IDL.Nat,
    'defectDefectB' : IDL.Nat,
    'cooperateDefectA' : IDL.Nat,
    'cooperateDefectB' : IDL.Nat,
    'cooperateCooperateA' : IDL.Nat,
    'cooperateCooperateB' : IDL.Nat,
    'defectCooperateA' : IDL.Nat,
    'defectCooperateB' : IDL.Nat,
  });
  const Decision = IDL.Record({ 'firmA' : IDL.Bool, 'firmB' : IDL.Bool });
  const RoundResult = IDL.Record({
    'cumulativeA' : IDL.Nat,
    'cumulativeB' : IDL.Nat,
    'decision' : Decision,
    'round' : IDL.Nat,
    'payoffA' : IDL.Nat,
    'payoffB' : IDL.Nat,
  });
  const SimulationResult = IDL.Record({
    'sustainedCooperation' : IDL.Bool,
    'totalA' : IDL.Nat,
    'totalB' : IDL.Nat,
    'rounds' : IDL.Vec(RoundResult),
  });
  
  return IDL.Service({
    'getAnalysis' : IDL.Func(
        [],
        [
          IDL.Record({
            'nashEquilibrium' : IDL.Text,
            'dominantStrategyA' : IDL.Text,
            'dominantStrategyB' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getPayoffMatrix' : IDL.Func([], [PayoffMatrix], ['query']),
    'getSimulationHistory' : IDL.Func(
        [],
        [IDL.Vec(SimulationResult)],
        ['query'],
      ),
    'runOneShot' : IDL.Func([IDL.Text, IDL.Text], [SimulationResult], []),
    'runRepeatedGame' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [SimulationResult],
        [],
      ),
    'updatePayoffMatrix' : IDL.Func([PayoffMatrix], [], []),
  });
};

export const init = ({ IDL }) => { return []; };